"""
demos.dcm_mt_random_walk - color gradient for a tree generated by the
        multi-threaded first entrance random walk algorithm
Eric Conrad
Copyright ©2024 by Eric Conrad.  Licensed under GPL.v3.

DESCRIPTION

    This demo produces a distance-colored maze.

LICENSE

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import os

from matplotlib.colors import to_rgb
from demos.colormap import main as sketch_example
from mazes.Algorithms.mt_random_walk import MTRandomWalk

ROWS = 13
COLS = 21
CENTER = 'c'
CARVER = (MTRandomWalk, (3,), {})

HOT = to_rgb("crimson")
COLD = to_rgb("skyblue")
ZERO = to_rgb("goldenrod")

basename = os.path.basename(__file__).split('.')[0]
pathname = "gallery/" + basename + ".png"

spider = sketch_example(ROWS, COLS, HOT, COLD, ZERO, CENTER, CARVER)
spider.title("Multi-threaded First Entrance Random Walk Spanning Tree")
spider.fig.tight_layout()
spider.save_image(filename=pathname)
print(f"saved image to: {pathname}")

# end module demos.dcm_mt_random_walk
